#!/bin/sh

#extrace
#tar xvf /usr/src/exfat-dkms.tar.bz2
#use dkms to add driver
#update module list
#depmod -aq


CVERSION=`dpkg-query -W -f='${Version}' exfat-source | awk -F "-" '{print $1}' | cut -d\: -f2`
TARGET_KERNEL_VERSION=`uname -r`
#DEBHELPER#
tar xvf /usr/src/exfat-dkms.tar.bz2 > /dev/null
ln -s /usr/src/modules/exfat-dkms /usr/src/exfat-$CVERSION-$TARGET_KERNEL_VERSION

case "$1" in
	configure)
		echo "Adding Module to DKMS build system"
		dkms add -m exfat -v $CVERSION-$TARGET_KERNEL_VERSION > /dev/null
		echo "Doing initial module build"
		#TODO: following will call : make KERNELRELEASE=3.13.0-35-generic;make install
		#the Makefile no good to handle it
		dkms build -m exfat -v $CVERSION-$TARGET_KERNEL_VERSION > /dev/null
		#echo "Installing initial module"
		#dkms install -m exfat -v $CVERSION-$TARGET_KERNEL_VERSION --force > /dev/null
		echo "Done."
	;;
esac
